---

- name: Setting the old nic naming system
  hosts: all
  tasks:
    - name: Read grub config file
      ansible.builtin.find:
        name: "/etc/default"
        patterns: "grub"
        file_type: file
        read_whole_file: true
        contains: 'net.ifnames=0.*biosdevname=0'
      register: grub_config_file

    - name: Modify grub configuration
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX=")(.*?)(")'
        line: '\1\2 net.ifnames=0 biosdevname=0\3'
        backrefs: yes
      when: grub_config_file.matched == 0
      notify: Update GRUB

  handlers:
    - name: Update GRUB
      ansible.builtin.command: update-grub

- name: Network setup
  hosts: all
  tasks:
    - name: "Set hostname based on inventory"
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: "debian"

